jwt:
  secret: ${JWT_SECRET:change-me-local-dev-secret-32chars}

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka