server:
  port: 8085

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${INVENTORY_DB_USERNAME:postgres}
    password: ${INVENTORY_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-service
      auto-offset-reset: latest

inventory:
  kafka:
    topics:
      reserved: ${INVENTORY_RESERVED_TOPIC:inventory-reserved}
      reservation-failed: ${INVENTORY_RESERVATION_FAILED_TOPIC:inventory-reservation-failed}

    retry:
      interval-ms: 2000
      max-retries: 2