apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ecommerce
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
