apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
      app.kubernetes.io/component: inventory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-service
        app.kubernetes.io/component: inventory
        app.kubernetes.io/part-of: ecommerce-microservices
    spec:
      containers:
        - name: inventory-service
          image: ecommerce/inventory-service:saga-read-model-v1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: JWT_SECRET
            - name: INVENTORY_DB_URL
              value: jdbc:postgresql://postgres-patroni-primary:5432/inventory_db
            - name: INVENTORY_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: patroni-inventory-db-username
            - name: INVENTORY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: patroni-inventory-db-password
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
