apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: inventory
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/component: inventory
  ports:
    - name: http
      port: 8085
      targetPort: http
      protocol: TCP
