{
 "title": "E-Commerce Microservices Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Microservice Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job!=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job!=\"prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orders Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecommerce_orders_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Orders Paid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ecommerce_orders_paid_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inventory Failed Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecommerce_orders_inventory_failed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Failed Orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ecommerce_orders_payment_failed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ecommerce_payments_succeeded_total",
     "legendFormat": "{{Succeeded}}"
    },
    {
     "expr": "ecommerce_payments_failed_total",
     "legendFormat": "{{Failed}}"
    }
   ]
  },
  {
   "title": "Inventory Reservation Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ecommerce_inventory_reservations_total",
     "legendFormat": "{{Created}}"
    },
    {
     "expr": "ecommerce_inventory_reservations_failed_total",
     "legendFormat": "{{Failed}}"
    },
    {
     "expr": "ecommerce_inventory_reservations_confirmed_total",
     "legendFormat": "{{Confirmed}}"
    },
    {
     "expr": "ecommerce_inventory_reservations_released_total",
     "legendFormat": "{{Released}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (application) (\r\n  rate(http_server_requests_seconds_count[5m])\r\n)",
     "legendFormat": "{{Application}}"
    }
   ]
  },
  {
   "title": "Average HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application) (\r\n  rate(http_server_requests_seconds_sum[5m])\r\n)\r\n/\r\nsum by (application) (\r\n  rate(http_server_requests_seconds_count[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (application) (\r\n  jvm_memory_used_bytes{area=\"heap\"}\r\n)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Average Payment Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ecommerce_payments_processing_seconds_sum[5m])\r\n/\r\nrate(ecommerce_payments_processing_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Inventory Reservation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ecommerce_inventory_reservation_processing_seconds_sum[5m])\r\n/\r\nrate(ecommerce_inventory_reservation_processing_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Order Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ecommerce_orders_creation_seconds_sum[5m])\r\n/\r\nrate(ecommerce_orders_creation_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}