apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: payment
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/component: payment
  ports:
    - name: http
      port: 8086
      targetPort: http
      protocol: TCP
