apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-patroni
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: postgres-patroni
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ecommerce
automountServiceAccountToken: true
