apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
