CREATE TABLE IF NOT EXISTS public.inventories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                             version BIGINT NOT NULL DEFAULT 0,

                             CONSTRAINT inventories_pkey
                             PRIMARY KEY (id),

    CONSTRAINT uk_inventories_product_id
    UNIQUE (product_id),

    CONSTRAINT chk_inventories_quantity
    CHECK (quantity >= 0),

    CONSTRAINT chk_inventories_reserved_quantity
    CHECK (reserved_quantity >= 0),

    CONSTRAINT chk_inventories_reserved_not_greater
    CHECK (reserved_quantity <= quantity)
    );

CREATE TABLE IF NOT EXISTS public.inventory_reservations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,

    reserved_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    released_at TIMESTAMP WITH TIME ZONE,

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

                             version BIGINT NOT NULL DEFAULT 0,

                             CONSTRAINT inventory_reservations_pkey
                             PRIMARY KEY (id),

    CONSTRAINT uk_inventory_reservation_order_product
    UNIQUE (order_id, product_id),

    CONSTRAINT fk_inventory_reservation_inventory
    FOREIGN KEY (product_id)
    REFERENCES public.inventories (product_id),

    CONSTRAINT chk_inventory_reservation_quantity
    CHECK (quantity > 0),

    CONSTRAINT chk_inventory_reservation_status
    CHECK (
              status IN (
              'RESERVED',
              'CONFIRMED',
              'RELEASED'
                        )
    )
    );

CREATE INDEX IF NOT EXISTS
    idx_inventory_reservations_order_status
    ON public.inventory_reservations (
    order_id,
    status
    );

CREATE TABLE IF NOT EXISTS public.processed_events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT processed_events_pkey
    PRIMARY KEY (id),

    CONSTRAINT uk_processed_events_order_id
    UNIQUE (order_id)
    );

CREATE TABLE IF NOT EXISTS public.inventory_outbox_events
(
    id UUID NOT NULL,

    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,

    event_type VARCHAR(150) NOT NULL,
    topic VARCHAR(150) NOT NULL,
    message_key VARCHAR(150) NOT NULL,

    payload TEXT NOT NULL,

    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,

    next_attempt_at TIMESTAMP WITH TIME ZONE
    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP WITH TIME ZONE
    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    published_at TIMESTAMP WITH TIME ZONE,

                               last_error VARCHAR(1000),

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT inventory_outbox_events_pkey
    PRIMARY KEY (id),

    CONSTRAINT uk_inventory_outbox_aggregate_event
    UNIQUE (
               aggregate_type,
               aggregate_id,
               event_type
           ),

    CONSTRAINT chk_inventory_outbox_retry_count
    CHECK (retry_count >= 0),

    CONSTRAINT chk_inventory_outbox_status
    CHECK (status IN ('PENDING', 'PUBLISHED'))
    );

CREATE INDEX IF NOT EXISTS idx_inventory_outbox_pending
    ON public.inventory_outbox_events (
    status,
    next_attempt_at,
    created_at
    );