CREATE TABLE IF NOT EXISTS public.payments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    order_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,

    amount NUMERIC(19, 2) NOT NULL,

    status VARCHAR(30) NOT NULL,

    failure_reason VARCHAR(500),
    failure_code VARCHAR(50),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,

                               version BIGINT NOT NULL DEFAULT 0,

                               CONSTRAINT payments_pkey
                               PRIMARY KEY (id),

    CONSTRAINT uk_payments_order_id
    UNIQUE (order_id),

    CONSTRAINT chk_payments_amount
    CHECK (amount > 0),

    CONSTRAINT chk_payments_status
    CHECK (
              status IN (
              'PENDING',
              'SUCCEEDED',
              'FAILED'
                        )
    ),

    CONSTRAINT chk_payments_completion_fields
    CHECK (
(
              status = 'PENDING'
              AND failure_code IS NULL
              AND failure_reason IS NULL
              AND completed_at IS NULL
)
    OR
(
    status = 'SUCCEEDED'
    AND failure_code IS NULL
    AND failure_reason IS NULL
    AND completed_at IS NOT NULL
)
    OR
(
    status = 'FAILED'
    AND failure_code IS NOT NULL
    AND failure_reason IS NOT NULL
    AND completed_at IS NOT NULL
)
    )
    );

CREATE TABLE IF NOT EXISTS public.processed_payment_events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT processed_payment_events_pkey
    PRIMARY KEY (id),

    CONSTRAINT uk_processed_payment_events_order_id
    UNIQUE (order_id)
    );

CREATE TABLE IF NOT EXISTS public.payment_outbox_events
(
    id UUID NOT NULL,

    aggregate_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,

    event_type VARCHAR(150) NOT NULL,
    topic VARCHAR(150) NOT NULL,
    message_key VARCHAR(150) NOT NULL,

    payload TEXT NOT NULL,

    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,

    next_attempt_at TIMESTAMP WITH TIME ZONE
    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP WITH TIME ZONE
    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    published_at TIMESTAMP WITH TIME ZONE,

                               last_error VARCHAR(1000),

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT payment_outbox_events_pkey
    PRIMARY KEY (id),

    CONSTRAINT uk_payment_outbox_aggregate_event
    UNIQUE (
               aggregate_type,
               aggregate_id,
               event_type
           ),

    CONSTRAINT chk_payment_outbox_retry_count
    CHECK (retry_count >= 0),

    CONSTRAINT chk_payment_outbox_status
    CHECK (status IN ('PENDING', 'PUBLISHED'))
    );

CREATE INDEX IF NOT EXISTS idx_payment_outbox_pending
    ON public.payment_outbox_events (
    status,
    next_attempt_at,
    created_at
    );