apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka-server
      app.kubernetes.io/component: service-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eureka-server
        app.kubernetes.io/component: service-discovery
        app.kubernetes.io/part-of: ecommerce-microservices
    spec:
      containers:
        - name: eureka-server
          image: ecommerce/eureka-server:k8s-cf4aa68
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8761
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
