apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/component: service-discovery
  ports:
    - name: http
      port: 8761
      targetPort: http
      protocol: TCP
