apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: product
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/component: product
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
