apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/component: customer
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-service
      app.kubernetes.io/component: customer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-service
        app.kubernetes.io/component: customer
        app.kubernetes.io/part-of: ecommerce-microservices
    spec:
      containers:
        - name: customer-service
          image: ecommerce/customer-service:k8s-26faf35
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://config-server:8888
            - name: CONFIG_SERVER_URL
              value: http://config-server:8888
            - name: EUREKA_DEFAULT_ZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: customer-service
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: JWT_SECRET
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: INTERNAL_API_KEY
            - name: CUSTOMER_DB_URL
              value: jdbc:postgresql://postgres-patroni-primary:5432/customer_db
            - name: CUSTOMER_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: patroni-customer-db-username
            - name: CUSTOMER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: patroni-customer-db-password
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
