apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: ecommerce-microservices
type: Opaque
stringData:
  JWT_SECRET: REPLACE_WITH_A_STRONG_JWT_SECRET
  INTERNAL_API_KEY: REPLACE_WITH_A_STRONG_INTERNAL_API_KEY
  CUSTOMER_DB_USERNAME: REPLACE_WITH_THE_CUSTOMER_DATABASE_USERNAME
  CUSTOMER_DB_PASSWORD: REPLACE_WITH_THE_CUSTOMER_DATABASE_PASSWORD
  ORDER_DB_USERNAME: REPLACE_WITH_THE_ORDER_DATABASE_USERNAME
  ORDER_DB_PASSWORD: REPLACE_WITH_THE_ORDER_DATABASE_PASSWORD
  INVENTORY_DB_USERNAME: REPLACE_WITH_THE_INVENTORY_DATABASE_USERNAME
  INVENTORY_DB_PASSWORD: REPLACE_WITH_THE_INVENTORY_DATABASE_PASSWORD
  PAYMENT_DB_USERNAME: REPLACE_WITH_THE_PAYMENT_DATABASE_USERNAME
  PAYMENT_DB_PASSWORD: REPLACE_WITH_THE_PAYMENT_DATABASE_PASSWORD
  patroni-superuser-username: CHANGE_ME
  patroni-superuser-password: CHANGE_ME
  patroni-replication-username: CHANGE_ME
  patroni-replication-password: CHANGE_ME
  patroni-customer-db-username: CHANGE_ME
  patroni-customer-db-password: CHANGE_ME
  patroni-order-db-username: CHANGE_ME
  patroni-order-db-password: CHANGE_ME
  patroni-inventory-db-username: CHANGE_ME
  patroni-inventory-db-password: CHANGE_ME
  patroni-payment-db-username: CHANGE_ME
  patroni-payment-db-password: CHANGE_ME
