apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
  labels:
    app.kubernetes.io/part-of: ecommerce-microservices
type: Opaque
stringData:
  JWT_SECRET: REPLACE_WITH_A_STRONG_JWT_SECRET
  INTERNAL_API_KEY: REPLACE_WITH_A_STRONG_INTERNAL_API_KEY
  patroni-superuser-username: CHANGE_ME
  patroni-superuser-password: CHANGE_ME
  patroni-replication-username: CHANGE_ME
  patroni-replication-password: CHANGE_ME
  patroni-customer-db-username: CHANGE_ME
  patroni-customer-db-password: CHANGE_ME
  patroni-order-db-username: CHANGE_ME
  patroni-order-db-password: CHANGE_ME
  patroni-inventory-db-username: CHANGE_ME
  patroni-inventory-db-password: CHANGE_ME
  patroni-payment-db-username: CHANGE_ME
  patroni-payment-db-password: CHANGE_ME
