apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-persistence-test
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: storage-persistence-test
    app.kubernetes.io/component: storage-test
    app.kubernetes.io/part-of: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
